name: CI
on:
  push:
    branches:
      - master
jobs:
  ci:
    name: Build + Test
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.14
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
      id: go

    - name: Check out source code
      uses: actions/checkout@v2

    - name: Build
      run: make build

    - name: Test
      run: make test

    - name: Bump and Tag Version
      uses: anothrNick/github-tag-action@1.22.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEFAULT_BUMP: patch
        WITH_V: true
