name: Dev CI
on:
  push:
    branches-ignore:
      - main
jobs:
  ci:
    name: Build + Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Build
        run: make clean build

      - name: Test
        run: make clean test
