name: Dev CI
on:
  push:
    branches-ignore:
      - master
jobs:
  ci:
    name: Build + Test
    runs-on: ubuntu-latest
    steps:

    - name: Check out source code
      uses: actions/checkout@v2.3.1

    - name: Set up Go 1.15
      uses: actions/setup-go@v1
      with:
        go-version: 1.15
      id: go

    - name: Build
      run: make clean build

    - name: Test
      run: make clean test
